#!/bin/sh

set -e

# Extract the base64 encoded config data and write this to the KUBECONFIG
echo "STARTING"
echo "YXBpVmVyc2lvbjogdjENCmNsdXN0ZXJzOg0KLSBjbHVzdGVyOg0KICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNdmFrTkRRV1ZoWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBWUldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkplazFFUlhsT2VrVXhUV3BSZUU1R2IxaEVWRTE2VFVSRmVVNUVSVEZOYWxGNFRrWnZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZVE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJWQkJSRU5EUVZGdlEyZG5SVUpCVERCV0NqTjBTRkZFTUUxSVNqSnNkRWhKTTNSRFVXWk1UMWgxY1M5RFQySktZa1ZoVmpabFRXbFJZMFIzY1hKVFEySnllazFGTTFVMVpUbFRhVUUyZVNzeFVYQUtNVlExZUZaa01XUTRUMWxOY1hOcFVGaExjazFaYXpZeWJXd3pZbmhvTjB0UVQwOXBTR28yYTJzM2VERlBaVnBGV1ROSmVrVkxTRlpLVFc5clkwcGFTQXBLTTB0dlEyNXdkMnhaTlN0NlZHOTRkQ3R2U0RGcGRYRjRUM294VG01cVQyaFJaMFk0SzNwTk5EY3ZNREo1ZDJSVFRGUjZia05HV2tKeUx6VmtSVVZuQ21sMFowZEpMMFUyTHl0WVQzUlZaVTFFU2xkTVRERTNhVUUxVERCeFMwVkxVRzFqYlZNMlEyUmtiakY1ZEZkRUszVlFNMkZZTDBKQlYyTmxRbTlYUm1rS1VHWmFNMWhNYkhOWFJFUk9aMjB6UkdkR1NtSmFWRVZTUTBGcWJXOWlhVEI1ZURCU2ExTjBTMHh1VHpBM1RtSkJkekphTWtkVWRqQnVLM0JsTkdOeWVnbzNia0UxTTB4VU0xZFNabEJKTkVoRVlrOVZRMEYzUlVGQllVNWFUVVpqZDBSbldVUldVakJRUVZGSUwwSkJVVVJCWjB0clRVRTRSMEV4VldSRmQwVkNDaTkzVVVaTlFVMUNRV1k0ZDBoUldVUldVakJQUWtKWlJVWkZibkpsZEVWWGRHVXlVbGR1YVd0SmMya3hUREIxUkdwd00zUk5RbFZIUVRGVlpFVlJVVThLVFVGNVEwTnRkREZaYlZaNVltMVdNRnBZVFhkRVVWbEtTMjlhU1doMlkwNUJVVVZNUWxGQlJHZG5SVUpCUkdRMGNrNUxSWGMwVVZkNlYxcENXbXBIS3dwblduRjVkWGh0U1dkMmJDdFBjVEJLTXpkaldUTkpRVFUxWlVOWGFuUnBhV28yU1ZWMlZVaEZRVlpuWXpWbk5VOVpSelp2VkVReE1UQlJPSHBQUTFabENuWkplVUprVjBSVGNIcExTMGxRWTBOak16bHpkMmhPVlhSc1JGZDVOWE50TXpCRFJ6VnZZamRhZW13dmFWZzFPSGR1UVd4NVRHc3ZWMXA0ZUhveVZFRUtXWEZ4Y1VSa2NGZHJiRGhxYVdKSU5tVkhla1phZWxOc1l5dFlSWGQxVUhGSlVIaENTazgwWVhOeFIweENZVWhaZG5Kck9VZEVkbWw0TDJGdFRrRnlNQXBVZFdZeU0yVTNOazFWTkROcFNuSm5lRk5JV1ZGd1FrSldSVFY2ZDFJM05HbExOVVUwTjBsdFNIbGlTMWRvUzBKS1NFSlhUa05RUzBOc2JtdEtZVFp6Q25kblRuTTFaMjgwUjFWeGIyeFNPV3BMY2s5U2IzWXhkVTlKYzFacldXbzVLeXRHUnpnMFlrcDZiVGxLVUhsblUyRjBjRTlUYWlzeVZVa3hZWGs0V1VVS1VVMXZQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09DQogICAgc2VydmVyOiBodHRwczovL0QzN0IxNkE1NUJERDBCMUI4MThFNkQ4NjkxRDc1MEZFLmdyNy5ldS1jZW50cmFsLTEuZWtzLmFtYXpvbmF3cy5jb20NCiAgbmFtZTogYXJuOmF3czpla3M6ZXUtY2VudHJhbC0xOjQzMjg2NDMyMDc4ODpjbHVzdGVyL2NhLWF3cy00YXBwcy1jbHVzdGVyDQpjb250ZXh0czoNCi0gY29udGV4dDoNCiAgICBjbHVzdGVyOiBhcm46YXdzOmVrczpldS1jZW50cmFsLTE6NDMyODY0MzIwNzg4OmNsdXN0ZXIvY2EtYXdzLTRhcHBzLWNsdXN0ZXINCiAgICB1c2VyOiBhcm46YXdzOmVrczpldS1jZW50cmFsLTE6NDMyODY0MzIwNzg4OmNsdXN0ZXIvY2EtYXdzLTRhcHBzLWNsdXN0ZXINCiAgbmFtZTogYXJuOmF3czpla3M6ZXUtY2VudHJhbC0xOjQzMjg2NDMyMDc4ODpjbHVzdGVyL2NhLWF3cy00YXBwcy1jbHVzdGVyDQpjdXJyZW50LWNvbnRleHQ6IGFybjphd3M6ZWtzOmV1LWNlbnRyYWwtMTo0MzI4NjQzMjA3ODg6Y2x1c3Rlci9jYS1hd3MtNGFwcHMtY2x1c3Rlcg0Ka2luZDogQ29uZmlnDQpwcmVmZXJlbmNlczoge30NCnVzZXJzOg0KLSBuYW1lOiBhcm46YXdzOmVrczpldS1jZW50cmFsLTE6NDMyODY0MzIwNzg4OmNsdXN0ZXIvY2EtYXdzLTRhcHBzLWNsdXN0ZXINCiAgdXNlcjoNCiAgICBleGVjOg0KICAgICAgYXBpVmVyc2lvbjogY2xpZW50LmF1dGhlbnRpY2F0aW9uLms4cy5pby92MWJldGExDQogICAgICBhcmdzOg0KICAgICAgLSAtLXJlZ2lvbg0KICAgICAgLSBldS1jZW50cmFsLTENCiAgICAgIC0gZWtzDQogICAgICAtIGdldC10b2tlbg0KICAgICAgLSAtLWNsdXN0ZXItbmFtZQ0KICAgICAgLSBjYS1hd3MtNGFwcHMtY2x1c3Rlcg0KICAgICAgY29tbWFuZDogYXdzDQogICAgICBlbnY6DQogICAgICAtIG5hbWU6IEFXU19QUk9GSUxFDQogICAgICAgIHZhbHVlOiBjYXZlcmJ1bmQNCg=="
echo "$KUBE_CONFIG_DATA" #| base64 -d #> /tmp/config
export KUBECONFIG=/tmp/config

if [ -z ${KUBECTL_VERSION+x} ] ; then
    echo "Using kubectl version: $(kubectl version --client)"
else
    echo "Pulling kubectl for version $KUBECTL_VERSION"
    rm /usr/bin/kubectl
    curl -sL -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/"$KUBECTL_VERSION"/bin/linux/amd64/kubectl && \
        chmod +x /usr/bin/kubectl
    echo "Using kubectl version: $(kubectl version --client )"
fi

if [ -z ${IAM_VERSION+x} ] ; then
    echo "Using aws-iam-authenticator version: $(aws-iam-authenticator version)"
else
    echo "Pulling aws-iam-authenticator for version $IAM_VERSION"
    rm /usr/bin/aws-iam-authenticator
    curl -sL -o /usr/bin/aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v"$IAM_VERSION"/aws-iam-authenticator_"$IAM_VERSION"_linux_amd64 && \
    chmod +x /usr/bin/aws-iam-authenticator
    echo "Using aws-iam-authenticator version: $(aws-iam-authenticator version)"
fi
#sh -c "kubectl version"
#echo "view content of kubectl config"
#sh -c "kubectl cluster-info"
#sh -c "kubectl $*"

